### ISSUE TITLE
Serializators?

### ISSUE THREAD

**Issue by emptyflask** [davydovanton/hanami-serializer#4]
I think it's fine to use this word in the documentation as an amusing variable name, but why make it a method name? If you must keep it, please at least make it an alias for `serializer`, which is much less confusing.

**Comment by davydovanton** [comment]
Hey!
Sorry but I'm not sure that I understand you correctly. Could you explain your idea more?

**Comment by FoboCasteR** [comment]
@davydovanton 
Hi!
"Serializator" looks like transliterated "сериализатор" :) In English there is no such word. It would be correct to use "serializer".

**Comment by emptyflask** [comment]
Ah, that makes sense. I didn't realize @davydovanton is in Moscow and is translating terms from Russian to English.
